name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_actions }}
        COMMIT_MSG: |
          "deploy niuai-docs"
          skip-checks: true
      run: |
        git --version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run docs:build
        npm test
      env:
        CI: true
