name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: '${{ secrets.github_actions }}'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        git --version
        npm ci
        npm run docs:build --if-present
        npm test
      env:
        CI: true
