name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run docs:build
        npm test
    - name: Commit to repository
      run: |
        cd docs/.vuepress/dist
        git config --global user.email "jiabinzhou@outlook.com"
        git config --global user.name "niuai"
        git init
        git add -A
        git commit -m 'deploy niuai-docs'
        git push -f https://x-access-token:${{ secrets.github_actions }}@github.com/niuai/blog.git master:gh-pages
      env:
        CI: true
